# Generated by Django 4.2.6 on 2023-10-14 08:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Floor",
            fields=[
                (
                    "number",
                    models.IntegerField(
                        auto_created=True,
                        default=1,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("isActive", models.BooleanField(default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "name",
                    models.CharField(
                        auto_created=True,
                        default="A",
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("isActive", models.BooleanField(default=True)),
                (
                    "floor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="parking.floor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("isOccupied", models.BooleanField(default=False)),
                ("isAllocated", models.BooleanField(default=False)),
                ("isActive", models.BooleanField(default=True)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="parking.section",
                    ),
                ),
            ],
        ),
    ]
