# Generated by Django 4.2.7 on 2024-02-12 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='section',
        ),
        migrations.RemoveField(
            model_name='section',
            name='floor',
        ),
        migrations.RenameField(
            model_name='parking',
            old_name='floorsCount',
            new_name='availableSlots',
        ),
        migrations.RenameField(
            model_name='parking',
            old_name='locationsCount',
            new_name='totalSlots',
        ),
        migrations.RemoveField(
            model_name='parking',
            name='sectionsCount',
        ),
        migrations.DeleteModel(
            name='Floor',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
