# Generated by Django 4.2.7 on 2024-01-28 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkomateuser',
            name='organization',
        ),
    ]
