# Generated by Django 4.2.7 on 2024-01-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_parkomateuser_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkomateuser',
            name='profilePicture',
            field=models.ImageField(blank=True, null=True, upload_to='profile-pictures/'),
        ),
    ]
