# Generated by Django 4.2.7 on 2024-01-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_parkomateuser_profilepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkomateuser',
            name='profilePicture',
            field=models.URLField(blank=True, default='https://img.icons8.com/fluency-systems-regular/96/user--v1.png', null=True),
        ),
    ]
