# Generated by Django 4.2.7 on 2024-01-26 10:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '__first__'),
        ('vehicle', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicleType', models.CharField(blank=True, max_length=50, null=True)),
                ('ownerAddress', models.CharField(blank=True, max_length=500, null=True)),
                ('permitNo', models.CharField(blank=True, max_length=150, null=True)),
                ('permitType', models.CharField(blank=True, max_length=150, null=True)),
                ('permitValidityFrom', models.DateField(blank=True, null=True)),
                ('permitValidityTo', models.DateField(blank=True, null=True)),
                ('registrationDate', models.DateField(blank=True, null=True)),
                ('registrationNumber', models.CharField(blank=True, max_length=250, null=True)),
                ('insurancePolicyNo', models.CharField(blank=True, max_length=250, null=True)),
                ('ownerMobileNo', models.CharField(blank=True, max_length=250, null=True)),
                ('insuranceName', models.CharField(blank=True, max_length=250, null=True)),
                ('permanentAddress', models.CharField(blank=True, max_length=500, null=True)),
                ('ownerName', models.CharField(blank=True, max_length=250, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=250, null=True)),
                ('manufacturerModel', models.CharField(blank=True, max_length=250, null=True)),
                ('pucValidUpto', models.DateField(blank=True, null=True)),
                ('fuelType', models.CharField(blank=True, max_length=250, null=True)),
                ('seatingCapacity', models.CharField(blank=True, max_length=250, null=True)),
                ('registeredPlace', models.CharField(blank=True, max_length=250, null=True)),
                ('fatherName', models.CharField(blank=True, max_length=250, null=True)),
                ('currentAddress', models.CharField(blank=True, max_length=500, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicleDetails', to='vehicle.vehicle')),
            ],
            options={
                'verbose_name_plural': 'Vehicle Details',
                'db_table': 'vehicle_details',
                'ordering': ['-registrationDate'],
            },
        ),
        migrations.CreateModel(
            name='PerHourVehicleCount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicleType', models.CharField(max_length=50)),
                ('vehicleCount', models.IntegerField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='per_hour_vehicle_count', to='organization.organization')),
            ],
            options={
                'verbose_name_plural': 'Per Hour Vehicle Count',
                'db_table': 'per_hour_vehicle_count',
                'ordering': ['-createdAt'],
            },
        ),
    ]
