# Generated by Django 4.2.7 on 2024-02-25 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_vehicledetails_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicledetails',
            options={'ordering': ['-insurance_validity', '-puc_valid_upto', '-id'], 'verbose_name_plural': 'Vehicle Details'},
        ),
        migrations.RenameField(
            model_name='vehicledetails',
            old_name='puc_valid_type',
            new_name='puc_valid_upto',
        ),
    ]
