# Generated by Django 4.2 on 2023-08-27 09:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("entry_gates", models.IntegerField(blank=True, null=True)),
                ("exit_gates", models.IntegerField(blank=True, null=True)),
                ("total_slots", models.IntegerField(blank=True, null=True)),
                ("filled_slots", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
