# Generated by Django 4.2 on 2023-10-09 19:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("address", models.TextField(blank=True, null=True)),
                ("entry_gates", models.IntegerField(blank=True, null=True)),
                ("exit_gates", models.IntegerField(blank=True, null=True)),
                ("total_slots", models.IntegerField(blank=True, null=True)),
                ("filled_slots", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "number_plate",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("cropped_image", models.URLField(blank=True, null=True, unique=True)),
                ("vehicle_image", models.URLField(blank=True, null=True, unique=True)),
                ("prediction", models.CharField(blank=True, max_length=255, null=True)),
                ("entry_time", models.DateTimeField(blank=True, null=True)),
                ("exit_time", models.DateTimeField(blank=True, null=True)),
                (
                    "entry_gate",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entry_gate",
                        to="api.gate",
                    ),
                ),
                (
                    "exit_gate",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exit_gate",
                        to="api.gate",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="gate",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gates",
                to="api.organization",
            ),
        ),
    ]
