# Generated by Django 4.2 on 2023-08-28 11:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="organization",
            name="address",
            field=models.TextField(default="MMCOE PUNE"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="organization",
            name="entry_gates",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="organization",
            name="exit_gates",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="organization",
            name="filled_slots",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="organization",
            name="name",
            field=models.CharField(default="MMCOE", max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="organization",
            name="total_slots",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number_plate", models.CharField(max_length=255, unique=True)),
                ("cropped_image", models.URLField(unique=True)),
                ("vehicle_image", models.URLField(unique=True)),
                ("prediction", models.CharField(max_length=255)),
                ("entry_time", models.DateTimeField(blank=True, null=True)),
                ("exit_time", models.DateTimeField(blank=True, null=True)),
                (
                    "entry_gate",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entry_gate",
                        to="api.gate",
                    ),
                ),
                (
                    "exit_gate",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exit_gate",
                        to="api.gate",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="gate",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gates",
                to="api.organization",
            ),
        ),
    ]
