# Generated by Django 4.2.7 on 2024-01-26 10:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number_plate', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('cropped_image', models.URLField(blank=True, null=True, unique=True)),
                ('vehicle_image', models.URLField(blank=True, null=True, unique=True)),
                ('prediction', models.CharField(blank=True, max_length=255, null=True)),
                ('entry_time', models.DateTimeField(blank=True, null=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('entry_gate', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entry_vehicle', to='organization.gate')),
                ('exit_gate', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exit_vehicke', to='organization.gate')),
            ],
        ),
    ]
