# Generated by Django 4.2.7 on 2024-02-16 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_alter_organization_admins'),
        ('vehicle', '0002_alter_vehicle_entry_gate_alter_vehicle_exit_gate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='exit_gate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exit_vehicle', to='organization.gate'),
        ),
    ]
