# Generated by Django 4.2.7 on 2024-02-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_alter_vehicle_options_alter_vehicle_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('economy', 'Economy'), ('midrange', 'Midrange'), ('premium', 'Premium')], max_length=255, null=True),
        ),
    ]
