# Generated by Django 4.2.7 on 2024-02-17 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_cctv'),
        ('vehicle', '0006_rename_prediction_vehicle_verified_number_plate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='parking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parking_vehicle', to='parking.parking'),
        ),
    ]
