# Generated by Django 4.2.7 on 2024-03-09 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0007_vehicle_parking'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='occurence_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
